### ISSUE TITLE
MQTT ERROR: error saving data on AiswaryaAdafruit/feeds/try2, value cannot be larger than 1024 bytes (1 KB) when feed history is on. 54820 bytes received

### ISSUE THREAD

**Issue by AISWARYA2019** [adafruit/adafruit-io-camera#3]
How to control the data rate (in bytes) that are being transferred from the camera to Adafruit dashboard??
Please help me by proving suitable Terminal commands.
Thanks.
![Uploading adafruit problem.JPG…]()

**Comment by vivekveeramani** [comment]
Hey @AISWARYA2019 , were you able to fix this issue?

**Comment by AISWARYA2019** [comment]
Yes, I fixed it. Thanks.

**Comment by Kludgester** [comment]
I have this same issue and it looks like a couple of recent comments need help too.  Could you please post the solution?

**Comment by gingershaped** [comment]
Same

**Comment by gingershaped** [comment]
@vivekveeramani @Kludgester 
FIGURED IT OUT

From the dashboard, click "Feeds" in the taskbar, and select the feed the image data is coming from. On the sidebar, find "Feed history" and set it to OFF.
